"""
Samba share plugin.
Manages Samba share configuration.
"""
from __future__ import annotations

import json
import os
import re
import shutil
from typing import Generator

from storage_plugins.base import StoragePlugin, CommandResult, PluginStatus


SHARE_NAME_PATTERN = re.compile(r"^[a-zA-Z0-9._-]+$")


class SambaPlugin(StoragePlugin):
    """Samba share management plugin."""

    PLUGIN_ID = "samba"
    PLUGIN_NAME = "Samba"
    PLUGIN_VERSION = "1.0.0"
    PLUGIN_DESCRIPTION = "Share folders over SMB/CIFS"
    PLUGIN_CATEGORY = "share"

    def __init__(self, config_dir: str):
        super().__init__(config_dir)
        self._schema = None

    def get_schema(self) -> dict:
        if self._schema is None:
            self._schema = {
                "type": "object",
                "properties": {
                    "shares": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "path": {"type": "string"},
                                "read_only": {"type": "boolean"},
                                "guest_ok": {"type": "boolean"},
                                "valid_users": {"type": "string"}
                            },
                            "required": ["name", "path"]
                        }
                    }
                }
            }
        return self._schema

    def get_config(self) -> dict:
        if os.path.exists(self.config_path):
            with open(self.config_path) as handle:
                return json.load(handle)
        return {"shares": []}

    def set_config(self, config: dict) -> CommandResult:
        try:
            os.makedirs(os.path.dirname(self.config_path), exist_ok=True)
            temp_path = f"{self.config_path}.tmp"
            with open(temp_path, "w") as handle:
                json.dump(config, handle, indent=2)
            os.replace(temp_path, self.config_path)
            return CommandResult(success=True, message="Configuration saved")
        except Exception as exc:
            return CommandResult(success=False, message="", error=str(exc))

    def validate_config(self, config: dict) -> list[str]:
        errors = []
        shares = config.get("shares", [])
        names = []

        for share in shares:
            name = share.get("name", "").strip()
            path = share.get("path", "").strip()

            if not name:
                errors.append("Share name is required")
            elif not SHARE_NAME_PATTERN.match(name):
                errors.append(f"Invalid share name: {name}")
            elif name in names:
                errors.append(f"Duplicate share name: {name}")
            names.append(name)

            if not path:
                errors.append(f"Share '{name}' requires a path")
            elif not path.startswith("/"):
                errors.append(f"Share path must be absolute: {path}")

        return errors

    def apply_config(self) -> CommandResult:
        config = self.get_config()
        errors = self.validate_config(config)
        if errors:
            return CommandResult(
                success=False,
                message="",
                error=f"Validation failed: {'; '.join(errors)}"
            )

        shares = config.get("shares", [])
        if not shares:
            return CommandResult(success=False, message="", error="No shares configured")

        config_path = os.path.join(self.config_dir, "samba.generated.conf")
        try:
            os.makedirs(self.config_dir, exist_ok=True)
            with open(config_path, "w") as handle:
                handle.write(self._generate_smb_config(shares))
            return CommandResult(
                success=True,
                message=f"Generated Samba config at {config_path}"
            )
        except Exception as exc:
            return CommandResult(success=False, message="", error=str(exc))

    def _generate_smb_config(self, shares: list[dict]) -> str:
        lines = [
            "# Generated by Pi-Health",
            "# Copy sections into /etc/samba/smb.conf and restart smbd",
            ""
        ]
        for share in shares:
            name = share.get("name", "")
            path = share.get("path", "")
            read_only = "yes" if share.get("read_only", False) else "no"
            guest_ok = "yes" if share.get("guest_ok", False) else "no"
            valid_users = share.get("valid_users", "").strip()

            lines.extend([
                f"[{name}]",
                f"   path = {path}",
                f"   read only = {read_only}",
                f"   guest ok = {guest_ok}"
            ])
            if valid_users:
                lines.append(f"   valid users = {valid_users}")
            lines.append("")

        return "\n".join(lines)

    def get_status(self) -> dict:
        if not self.is_installed():
            return {
                "status": PluginStatus.ERROR.value,
                "message": "Samba is not installed",
                "details": {}
            }

        config = self.get_config()
        shares = config.get("shares", [])

        if not shares:
            return {
                "status": PluginStatus.UNCONFIGURED.value,
                "message": "No shares configured",
                "details": {"shares": []}
            }

        return {
            "status": PluginStatus.HEALTHY.value,
            "message": f"{len(shares)} share(s) configured",
            "details": {"shares": shares}
        }

    def get_commands(self) -> list[dict]:
        return []

    def run_command(self, command_id: str, params: dict = None) -> Generator[str, None, CommandResult]:
        yield "No commands available for Samba plugin.\n"
        return CommandResult(success=False, message="", error="No commands available")

    def is_installed(self) -> bool:
        return shutil.which("smbd") is not None

    def get_install_instructions(self) -> str:
        return "Install Samba: apt-get install samba / dnf install samba / pacman -S samba"
